####################################
# GLOBAL PARAMETERS                #
####################################

global_parameters: 
  random_seed: 123 # specify a random seed for reproducibility
  chromosome: 1 # specify `all` or give a number from 1 to 22
  superpopulation: "EUR" # if creating data for a specific superpopulation, choose from `AFR`, `AMR`, `EAS`, `EUR`, `SAS` (otherwise set to `none`)


####################################
# FILEPATHS                        #
####################################

# - the chromosome number can be given as a wildcard by specifying {chromosome} in the filepath
# - the superpopulation can be given as a wildcard by specifying {superpopulation} in the filepath
filepaths:
  vcf_input_raw: data/inputs/raw/1KGPhase3.chr{chromosome}.vcf.gz
  vcf_input_processed_prefix: data/inputs/processed/1KGPhase3.chr{chromosome}.hapmap
  vcf_input_processed: data/inputs/processed/1KGPhase3.chr{chromosome}.hapmap.recode.vcf
  variant_list: data/external/variant_lists/hapmap_variant_list_chr{chromosome}.txt
  genetic_mapfile: data/inputs/raw/genetic_maps/chr{chromosome}.interpolated_genetic_map
  genetic_distfile: data/inputs/processed/1KGPhase3.chr{chromosome}.hapmap.distfile
  hap1_matrix: data/inputs/processed/1KGPhase3.chr{chromosome}.hapmap.h1
  hap2_matrix: data/inputs/processed/1KGPhase3.chr{chromosome}.hapmap.h2
  vcf_metadata: data/inputs/processed/1KGPhase3.chr{chromosome}.metadata
  popfile_raw: data/inputs/raw/1KGPhase3.pop.panel
  popfile_processed: data/inputs/processed/1KGPhase3.pop.panel
  synthetic_data_prefix: data/outputs/test/test{chromosome}
  evaluation_output: data/outputs/test/evaluation/test{chromosome}
  optimisation_output: data/outputs/test/optimisation/test{chromosome}
  reference_dir: data/inputs/reference
  causal_list: /path/to/the/causal/SNP/list
  sample_list: /path/to/the/sample/file
  pheno_reference: /path/to/the/reference/file


software_paths:
    plink: software/plink
    plink2: software/plink2
    king: software/king
    vcftools: vcftools
    mapthin: software/mapthin


####################################
# GENOTYPE DATA                    #
####################################

#   You can heavily customise population structure/admixture of the synthetic data
#   by creating a list of custom population groups with the following parameters:
#
#   `id`:          a name for your custom population group, e.g. `example1`
#   `numsamples`:  the number of samples you want to generate for this population group, e.g. 100
#   `populations`: the population structure/admixture composition for the population group,
#                  as a list of superpopulation/population codes (based on the 1000 Genomes dataset)
#                  that you want to include, and their corresponding proportions (which must sum to 100)
#
#                  for example, if you want to generate 100 genotypes with EUR ancestry and 200
#                  genotypes with AFR ancestry, you could write
#                   
#                   - id: EUR_pop
#                     nsamples: 100
#                     populations:
#                       - EUR: 100
#                   - id: AFR_pop
#                     nsamples: 200
#                     populations:
#                       - AFR: 100
#
#                 or, if you wanted 100 admixed genotypes where each genotype is composed of 50% 
#                 EUR ancestry and 50% AFR ancestry, you could write
#                 
#                   - id: admix_pop
#                     nsamples: 100
#                     populations:
#                       - EUR: 50
#                       - AFR: 50
#
#                you can specify custom population groups using *either* superpopulations or populations, 
#                but you cannot mix superpopulations and populations within the same custom population group
#                (see a list of codes at the bottom of this document)
genotype_data:
  filetype: plink # specify either `plink` or `vcf` - note that `plink` means bed/bim/fam format
  batchsize: 1000 # batchsize is only needed for `plink` output - batchsize value will be ignored for `vcf`
  samples:
    use_default: true
    custom:
      - id: examplepop1
        nsamples: 1000
        populations: 
          - EUR: 100
      - id: examplepop2
        nsamples: 500
        populations:
          - GBR: 30
          - IBS: 70
    default:
      nsamples: 1000 # code will use superpopulation specified by global variable
  # recombination rate (default values were determined by our optimisation procedure)
  rho:
    AFR: 0.001 # default 0.001
    AMR: 0.001 # default 0.001
    EAS: 0.001 # default 0.001
    EUR: 0.001 # default 0.001
    SAS: 0.001 # default 0.001
  # mean of effective population size (default values were determined by our optimisation procedure)
  Ne:
    AFR: 2000 # default 2000
    AMR: 2000 # default 2000
    EAS: 2000 # default 2000
    EUR: 2000 # default 2000
    SAS: 2000 # default 2000

# TODO replace default parameter values after running likelihood free inference optimisation

####################################
# PHENOTYPE DATA                   #
####################################

phenotype_data:
  heritability: 0.5,0.6
  prevalence: 0.1,0.2
  a: -0.4 
  b: -0.5
  c: 0.5
  n_component: 3
  comp_weight: 1,2,4
  pop_covar: 1,1,1,1 
  polygenicity: 0.05 

####################################
# EVALUATION                       #
####################################

# Specify which metrics you want to use by setting the value to true
evaluation:
  metrics:
    aats:     true  # nearest neighbour adversarial accuracy
    kinship:  true  # kinship relatedness
    ld:       true  # linkage disequilibrium
    maf:      true  # minor allele frequency divergences
    pca:      true  # principal components analysis


####################################
# OPTIMISATION                     #
####################################

# configuration for likelihood free inference optimisation procedure
# note that this code uses a single superpopulation and ignores custom population structures
optimisation:
  # prior distributions - specify lower/upper bounds for uniform priors
  priors:
    rho:
      uniform_lower: 0
      uniform_upper: 0.1
    Ne:
      uniform_lower: 1000
      uniform_upper: 50000
  # inference type - simulation-based rejection ABC or emulation-based rejection ABC
  simulation_rejection_ABC:
    run: true
    n_particles: 500
    threshold: 0.05
    max_iter: 10
    write_progress: true
  emulation_rejection_ABC:
    run: false
    n_particles: 500
    threshold: 0.05
    n_design_points: 50
    max_iter: 10000
    write_progress: true
  # choice of summary statistic/s
  summary_statistics:
    ld_decay: true
    kinship: false

####################################
# ADDITIONAL INFORMATION           #
####################################

# superpopulation code list:
#
#   AFR African
#   AMR Admixed American
#   EAS East Asian
#   EUR European
#   SAS South Asian
#
#
# population code list:
# 
#   CHB Han Chinese             Han Chinese in Beijing, China
#   JPT Japanese                Japanese in Tokyo, Japan
#   CHS Southern Han Chinese    Han Chinese South
#   CDX Dai Chinese             Chinese Dai in Xishuangbanna, China
#   KHV Kinh Vietnamese         Kinh in Ho Chi Minh City, Vietnam
#   CHD Denver Chinese          Chinese in Denver, Colorado (pilot 3 only)

#   CEU CEPH                    Utah residents (CEPH) with Northern and Western European ancestry 
#   TSI Tuscan                  Toscani in Italia 
#   GBR British                 British in England and Scotland 
#   FIN Finnish                 Finnish in Finland 
#   IBS Spanish                 Iberian populations in Spain 

#   YRI Yoruba                  Yoruba in Ibadan, Nigeria
#   LWK Luhya                   Luhya in Webuye, Kenya
#   GWD Gambian                 Gambian in Western Division, The Gambia 
#   MSL Mende                   Mende in Sierra Leone
#   ESN Esan                    Esan in Nigeria

#   ASW African-American SW     African Ancestry in Southwest US  
#   ACB African-Caribbean       African Caribbean in Barbados
#   MXL Mexican-American        Mexican Ancestry in Los Angeles, California
#   PUR Puerto Rican            Puerto Rican in Puerto Rico
#   CLM Colombian               Colombian in Medellin, Colombia
#   PEL Peruvian                Peruvian in Lima, Peru

#   GIH Gujarati                Gujarati Indian in Houston, TX
#   PJL Punjabi                 Punjabi in Lahore, Pakistan
#   BEB Bengali                 Bengali in Bangladesh
#   STU Sri Lankan              Sri Lankan Tamil in the UK
#   ITU Indian                  Indian Telugu in the UK