# filepath and filename configurations
filepaths:
  input_directory:          data/inputs
  output_directory:         data/outputs/test
  synthetic_data_prefix:    test

# software
software_paths:
  plink:                    software/plink
  king:                     software/king

# global parameters
global_parameters: 
  random_seed:              123  # for reproducibility (note that all chromosomes part of the same dataset must use the same seed number)
  chromosome:               all   # specify `all` or give a specific number from 1 to 22
