# configuration for likelihood free inference optimisation procedure
optimisation:
  # prior distributions - specify lower/upper bounds for uniform priors
  priors:
    rho:
      uniform_lower: 0
      uniform_upper: 0.1
    Ne:
      uniform_lower: 1000
      uniform_upper: 50000
  # inference type - simulation-based rejection ABC or emulation-based rejection ABC
  inference_type:
    simulation_rejection_ABC: true
      n_particles: 500
      threshold: 0.05
      max_iter: 100
      write_progress: true
    emulation_rejection_ABC: true
      n_particles: 500
      threshold: 0.05
      n_design_points: 50
      max_iter: 10000
      write_progress: true
  # choice of summary statistic/s
  summary_statistics:
    ld_decay: true
    kinship: true
  # choice of superpopulation/s
  superpopulations:
    AFR: true
    AMR: true
    EAS: true
    EUR: true
    SAS: true
